app:
  trello:
    token: ba9e4ca4449a203ebf3f9e6c7cedbff279acb2a1abfa0370ba8c1ea3de3ed71d
    publicKey: 0946a64172e1eb5c7468da3b772fa43e
  google:
    credentials:
      client_id: "1002984376432-2gifjprv666qfp6lcbil0mri0m73rb10.apps.googleusercontent.com"
      project_id: "spiderman-181210"
      auth_uri: "https://accounts.google.com/o/oauth2/auth"
      token_uri: "https://accounts.google.com/o/oauth2/token"
      auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
      client_secret: "0U7VdodzVaZ99dKGf8kNrR9j"
      redirect_uris: ["urn:ietf:wg:oauth:2.0:oob","http://localhost"]
    gmail:
      target_email: yanbin.ge@striking.ly